const VARIABLE = {
    GET_STARTED: "GET_STARTED",
    MAIN_MENU: "MAIN_MENU",
    GUID_TO_USE: "GUID_TO_USE",
    RESTART_BOT: "RESTART_BOT",
    LUNCH_MENU: "LUNCH_MENU",
    DINNER_MENU: "DINNER_MENU",
    VIEW_APPETIZER_LUCH: "VIEW_APPETIZER_LUNCH",
    VIEW_APPETIZER_DINNER: "VIEW_APPETIZER_DINNER",
    VIEW_MAIN_DISHES_LUNCH: "VIEW_MAIN_DISHES_LUNCH",
    VIEW_MAIN_DISHES_DINNER: "VIEW_MAIN_DISHES_DINNER",
    VIEW_DESSERTS_LUNCH: "VIEW_DESSERTS_LUNCH",
    VIEW_DESSERTS_DINNER: "VIEW_DESSERTS_DINNER",
    VIEW_DETAIL: "VIEW_DETAIL", //khong gian nha hang
    GO_BACK_MAIN: "GO_BACK_MAIN",
    GO_BACK_LUNCH_MENU: "GO_BACK_LUNCH_MENU",
    GO_BACK_DINNER_MENU: "GO_BACK_DINNER_MENU",
    VIEW_DETAIL_ROOMVJP: "VIEW_DETAIL_ROOMVJP",
    VIEW_DETAIL_ROOM: "VIEW_DETAIL_ROOM"

}

module.exports = VARIABLE